CREATE TABLE sba.loans_raw (
    loan_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    program TEXT,
    location_id TEXT,
    borr_name TEXT,
    borr_street TEXT,
    borr_city TEXT,
    borr_state TEXT,
    borr_zip TEXT,
    bank_name TEXT,
    bank_fdic_number TEXT,
    bank_ncua_number TEXT,
    bank_street TEXT,
    bank_city TEXT,
    bank_state TEXT,
    bank_zip TEXT,
    gross_approval NUMERIC(15 ,2),
    sba_guaranteed_approval NUMERIC(15, 2),
    approval_date DATE,
    approval_fiscal_year SMALLINT,
    first_disbursement_date DATE,
    processing_method TEXT,
    subprogram TEXT,
    initial_interest_rate NUMERIC(6, 3),
    fixed_or_variable_interest TEXT,
    term_in_months INTEGER,
    naics_code TEXT,
    naics_description TEXT,
    franchise_code TEXT,
    franchise_name TEXT,
    project_county TEXT,
    project_state TEXT,
    sba_district_office TEXT,
    congressional_district TEXT,
    business_type TEXT,
    business_age TEXT,
    loan_status TEXT,
    paid_in_full_date DATE,
    charge_off_date DATE,
    gross_charge_off_amount NUMERIC(15, 2),
    revolver_status BOOLEAN,
    jobs_supported INTEGER,
    collateral_ind TEXT,
    sold_secondary_mrkt TEXT
);